name: crickAdda
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  provider:
  flutter_localization: ^0.2.0
  pinput: ^5.0.0
  carousel_slider:
  image_picker:
  image_cropper: ^5.0.1
  file_picker:
  path_provider:
  http:
  another_flushbar: ^1.12.30
  flutter_widget_from_html:
  url_launcher: ^6.3.0
  install_plugin: ^2.1.0
  dio: ^5.4.0
  lottie:
  flutter_cashfree_pg_sdk: ^2.2.9+47
  share_plus: ^10.0.0
#  flutter_share: ^2.0.0
  web_socket_channel: ^2.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true

  uses-material-design: true
  assets:

    - assets/
    - assets/icons/
    - assets/players_img/
    - assets/ground.jpg
    - assets/rive/
    - assets/referlogo.png
    - assets/referbg.png

